apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  namespace: amq2
spec:
  clusters:
    - alias: my-cluster-source
      bootstrapServers: 'my-cluster-source-kafka-bootstrap.amq1.svc.cluster.local:9092'
    - alias: my-cluster-target
      bootstrapServers: 'my-cluster-target-kafka-bootstrap.amq2.svc.cluster.local:9092'
      config:
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  connectCluster: my-cluster-target
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      sourceCluster: my-cluster-source
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 1
          replication.factor: 3
          sync.topic.acls.enabled: 'false'
      targetCluster: my-cluster-target
      topicsPattern: .*
  replicas: 1
  version: 3.4.0