apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-target-user
  labels:
    strimzi.io/cluster: my-target-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Underlying Kafka Connects internal topics used to store configuration, offsets or status
      - resource:
          type: group
          name: mirrormaker2-cluster
        operations:
          - Read
      - resource:
          type: topic
          name: mirrormaker2-cluster-configs
        operations:
          - Read
          - Describe
          - DescribeConfigs
          - Write
          - Create
      - resource:
          type: topic
          name: mirrormaker2-cluster-status
        operations:
          - Read
          - Describe
          - DescribeConfigs
          - Write
          - Create
      - resource:
          type: topic
          name: mirrormaker2-cluster-offsets
        operations:
          - Read
          - Describe
          - DescribeConfigs
          - Write
          - Create
      # MirrorSourceConnector
      - resource: # Needed for every topic which is mirrored
          type: topic
          name: "*"
        operations:
          - Read
          - Write
          - AlterConfigs
          - Alter
          - Create
      # MirrorCheckpointConnector
      - resource:
          type: cluster
        operations:
          - Describe
      - resource:
          type: topic
          name: my-source-cluster.checkpoints.internal
        operations:
          - Describe
          - Write
          - Create
      - resource: # Needed for every group for which the offset is synced
          type: group
          name: "*"
        operations:
          - Read
          - Describe
      # MirrorHeartbeatConnector
      - resource:
          type: topic
          name: heartbeats
        operations:
          - Read
          - Describe
          - Write
          - Create