apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-rolebinding-namespace1
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: amq-streams  # Replace with the desired namespace
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io

