---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-streams-kafka-cluster

resources:
  - kafka-persistent.yaml
  - kafka-metrics-configmap.yaml
  - metrics-config.yaml
  - amq-streams-rolebinding.yaml
