apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: amq-streams
spec:
  replicas: 2
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  enableMetrics: true
  http:
    port: 8080
