apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: pscu-digital
  namespace: amq1
  labels:
    strimzi.io/cluster: my-cluster-source
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
  topicName: pscu-digital